### ISSUE TITLE
Download library error

### ISSUE THREAD

**Issue by longmouses233** [magicmq/pyspigot#7]
**Describe the bug**
Download library error

**To Reproduce**
1. open server , and wait...

**Expected behavior**
running success

**Additional Info (please fill in):**
 - Server environment: Spigot
 - Minecraft version 1.21
 - PySpigot version 0.6.0

**Additional context**
Log
[21:19:47] [Server thread/WARN]: [PySpigot] Error when attempting to get latest plugin version from Spigot:
[21:19:47] [Server thread/WARN]: java.net.SocketException: Connection reset
[21:19:47] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[21:19:47] [Server thread/WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1109)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readFully(SSLSocketInputRecord.java:472)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:243)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1678)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1602)
[21:19:47] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:19:47] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1325)
[21:19:47] [Server thread/WARN]: 	at dev.magicmq.pyspigot.PySpigot.fetchSpigotVersion(PySpigot.java:208)
[21:19:47] [Server thread/WARN]: 	at dev.magicmq.pyspigot.PySpigot.onEnable(PySpigot.java:135)
[21:19:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[21:19:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[21:19:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[21:19:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567)
[21:19:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481)
[21:19:47] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237)
[21:19:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[21:19:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[21:19:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by magicmq** [comment]
This is not really an error, but more of a warning that the plugin wasn't able to fetch the latest version from Spigot. It only affects the update notification system. The error should not affect plugin functionality.
